name: Code Cleanup & Testing

on:
  push:
    branches:
        - WR-54

jobs:
  autoflake:
    name: "Check imports (autoflake)"
    runs-on: ubuntu-latest
    environment: dev

    steps:
    - name: Check out code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'

    - name: Install autoflake
      run: pip install autoflake

    - name: Run autoflake check
      run: autoflake --check .

    - name: Show autoflake results
      run: autoflake .

  isort:
    name: "Sort imports (isort)"
    runs-on: ubuntu-latest
    environment: dev

    steps:
    - name: Check out code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'

    - name: Install isort
      run: pip install isort

    - name: Run isort
      run: isort .

  black:
    name: "Format code (black)"
    needs:
      - autoflake
      - isort
    runs-on: ubuntu-latest
    environment: dev

    steps:
    - name: Check out code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'

    - name: Install black
      run: pip install black

    - name: Run black
      run: black .

  flake:
    name: "Run linter (flake8)"
    needs: black
    runs-on: ubuntu-latest
    environment: dev

    steps:
    - name: Check out code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'

    - name: Install flake8
      run: pip install flake8

    - name: Run flake8
      run: flake8 .

  pylint:
    name: "Run static analysis (pylint)"
    needs: flake
    runs-on: ubuntu-latest
    environment: dev

    steps:
    - name: Check out code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'

    - name: Install pylint
      run: pip install pylint

    - name: Run pylint
      run: pylint .

  mypy:
    name: "Run type checker (mypy)"
    needs: flake
    runs-on: ubuntu-latest
    environment: dev

    steps:
    - name: Check out code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'

    - name: Install mypy
      run: pip install mypy

    - name: Run mypy
      run: mypy .
